### ISSUE TITLE
Logging in JSON format

### ISSUE THREAD

**Issue by pavelvodrazka** [tomcat-slf4j-logback/tomcat10-slf4j-logback#67]
Hi, I've created a PR to provide ability to log in JSON format via [logstash-logback-encoder](https://github.com/logfellow/logstash-logback-encoder).

PR https://github.com/tomcat-slf4j-logback/tomcat10-slf4j-logback/pull/66

**Comment by pavelvodrazka** [comment]
The motivation behind this pull-request is to provide an easy way to create Docker/K8s Tomcat containers with catalina and access logs in JSON format redirected to STDOUT.

Example `conf/logback.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender name="CONSOLE" class="org.apache.juli.logging.ch.qos.logback.core.ConsoleAppender">
        <!-- json encoder --> 
        <encoder class="org.apache.juli.logging.net.logstash.logback.encoder.LogstashEncoder" />
    </appender>

    <root level="INFO">
        <appender-ref ref="CONSOLE" />
    </root>

</configuration>
```

Example `conf/logback-access.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <!-- json encoder -->
        <encoder class="net.logstash.logback.encoder.LogstashAccessEncoder" />
    </appender>

    <appender-ref ref="CONSOLE" />

</configuration>
```

**Comment by hazendaz** [comment]
@pavelvodrazka I'm still working on getting this all together.  The upstream config and parent needed updates so we are handling files we need to include in the releases well.

As to the logstash access, is the expectation that its used as defined where users put jackson and logstash encoder into tomcat/lib?  Or was expectation that we might go further and use the wrapped off copies to avoid any classloader issues with apps?  Based on what you have there, I think its more the first way and to that end, we should document that fully as well as include the normal jars as well in our bundle so users can simply unzip and get best of both worlds.  If its the later were we try to isolate I half wonder if we try to isolate all of logback access as well so tomcat-juli just does it all - kind of a larger improvement.

**Comment by pavelvodrazka** [comment]
@hazendaz Originally I didn't give it much thought and blindly followed the initial state of this project, where only the Logback Core and Classic relocations were addressed. So I skipped Logback Access entirely and solved it additionally via tomcat/lib.

Considering the possible problems with dependencies and classloaders, it would definitely be better to add wrapped off Logback Access to tomcat-juli. It would also be a much more user friendly solution without dependency duplications.

I'm on vacation this week, but I could do additional PR next week if you want.

**Comment by hazendaz** [comment]
@pavelvodrazka Thanks for your feedback.  I'll plan to bring in the libraries wrapped entirely.  That way we are consistent in this new usage.  While not super obvious there could be conflicts with logback, I'm sure jackson would be higher potential, so best we simply make that so, document it well, and if users continue using the other provided ways those will work too.  So there will be more to testing but should be able to get out in early September.  Thanks and enjoy your vacation.

**Comment by pavelvodrazka** [comment]
Hi @hazendaz, is there anything new regarding your plan to wrap logback access dependencies? Anything I can help with?

**Comment by hazendaz** [comment]
Hi @pavelvodrazka not sure if I had mentioned or not.  Its not possible to wrap logback access libraries as the classloader is isolated for bin so that didn't pan out.  The code otherwise was good, I just had not had time to test the json support for logstash.  I tested that tonight and have pushed out the release.  It will be in maven central in next few hours.
